-- CREATE TABLE customer (
--                           id BIGINT PRIMARY KEY NOT NULL,
--                           first_name VARCHAR(255),
--                           last_name VARCHAR(255),
--                           birth_date DATE
-- );